# Generated by Django 3.1.1 on 2020-10-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_category_comment_contact_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='post',
        ),
    ]
