# Generated by Django 3.1.1 on 2020-10-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201026_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.FileField(blank=True, upload_to='media/%Y%m%d/'),
        ),
    ]
