# Generated by Django 3.1.1 on 2020-10-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_user_total_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created',), 'verbose_name': 'Following Relationship', 'verbose_name_plural': 'Following Relationships'},
        ),
    ]
