# Generated by Django 3.1.1 on 2020-10-30 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_auto_20201030_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followings',
            new_name='followee',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followee')},
        ),
    ]
