# Generated by Django 3.1.1 on 2020-11-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20201103_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Detail Visitor', 'verbose_name_plural': 'Visitors'},
        ),
    ]
