# Generated by Django 3.1.1 on 2020-11-03 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201103_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
