# Generated by Django 3.1.1 on 2020-11-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201103_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-created'], 'verbose_name': 'Detail Visitor', 'verbose_name_plural': 'Visitors'},
        ),
    ]
