# Generated by Django 3.1.1 on 2021-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_visitor_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.FileField(blank=True, default='avatar.png', upload_to='media/%Y%m%d/'),
        ),
    ]
